name: Ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache --unstable imports/mod.ts

      - name: Run Tests
        run: deno test -A --unstable
